"""
Send the daily dividend/split report via SMTP.
Supports Gmail and Outlook — host is auto-detected from the sender address.
Credentials are loaded from environment variables (see .env.example).
"""

import os
import smtplib
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path


def _smtp_settings(sender: str) -> tuple[str, int]:
    """Return (host, port) based on sender domain."""
    domain = sender.split('@')[-1].lower() if '@' in sender else ''
    if 'gmail' in domain:
        return 'smtp.gmail.com', 587
    if 'outlook' in domain or 'hotmail' in domain or 'live' in domain:
        return 'smtp-mail.outlook.com', 587
    # Default: Office 365 (covers custom domains on M365)
    return 'smtp.office365.com', 587

SENDER      = os.getenv('EMAIL_SENDER', '')
PASSWORD    = os.getenv('EMAIL_PASSWORD', '')
RECIPIENTS  = [r.strip() for r in os.getenv('EMAIL_RECIPIENTS', '').split(',') if r.strip()]


def send_report(
    report_date: datetime.date,
    csv_path: Path,
    html_body: str,
    discrepancies: list[str] | None = None,
) -> None:
    """
    Email the daily report with the CSV attached.

    html_body      : pre-built HTML summary of events
    discrepancies  : list of human-readable conflict descriptions (Python vs Claude)
    """
    if not SENDER or not PASSWORD:
        raise RuntimeError(
            "EMAIL_SENDER and EMAIL_PASSWORD must be set in environment. "
            "See .env.example for setup instructions."
        )
    if not RECIPIENTS:
        raise RuntimeError("EMAIL_RECIPIENTS must be set in environment (comma-separated).")

    subject = f"[Dividends & Splits] Report for {report_date.strftime('%B %d, %Y')}"

    msg = MIMEMultipart('mixed')
    msg['From']    = SENDER
    msg['To']      = ', '.join(RECIPIENTS)
    msg['Subject'] = subject

    # Build HTML body
    disc_section = ''
    if discrepancies:
        items = ''.join(f'<li style="color:#c0392b">{d}</li>' for d in discrepancies)
        disc_section = f"""
        <hr/>
        <h3 style="color:#c0392b">&#9888; Discrepancies — MANUAL VERIFICATION REQUIRED</h3>
        <p>The automated script and Claude's independent check disagreed on the following.
        Do <strong>not</strong> rely on either result until verified.</p>
        <ul>{items}</ul>
        """

    full_html = f"""
    <html><body style="font-family:Arial,sans-serif;font-size:14px;color:#222">
    <h2>Daily Dividend &amp; Stock Split Report</h2>
    <p><strong>Date checked:</strong> {report_date.strftime('%A, %B %d, %Y')}</p>
    {html_body}
    {disc_section}
    <hr/>
    <p style="font-size:11px;color:#888">Generated by JagAutomations · DividendsAndStockSplits</p>
    </body></html>
    """

    msg.attach(MIMEText(full_html, 'html'))

    # Attach CSV
    if csv_path and csv_path.exists():
        with open(csv_path, 'rb') as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', f'attachment; filename="{csv_path.name}"')
        msg.attach(part)

    smtp_host, smtp_port = _smtp_settings(SENDER)
    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(SENDER, PASSWORD)
        server.sendmail(SENDER, RECIPIENTS, msg.as_string())

    print(f"Email sent to: {', '.join(RECIPIENTS)}")


def build_html_body(
    splits:    dict[str, dict],   # {ticker: {'ratio': ..., 'sources': [...], 'originals': [...]}}
    dividends: dict[str, dict],   # {ticker: {'amount': ..., 'sources': [...], 'originals': [...]}}
    report_date: datetime.date,
) -> str:
    """Render the main HTML table section for the email body."""

    def source_badges(sources: list[str]) -> str:
        colors = {
            'NASDAQ': '#2980b9', 'TipRanks': '#27ae60',
            'NASDAQTrader': '#8e44ad', 'StockAnalysis': '#e67e22',
            'MarketBeat': '#c0392b', 'EarningsWhispers': '#16a085',
            'Claude': '#d35400',
        }
        badges = []
        for s in sources:
            c = colors.get(s, '#7f8c8d')
            badges.append(
                f'<span style="background:{c};color:#fff;padding:2px 6px;'
                f'border-radius:3px;font-size:11px;margin-right:3px">{s}</span>'
            )
        return ''.join(badges)

    # Splits table
    splits_rows = ''
    if splits:
        for ticker, info in sorted(splits.items()):
            originals = ', '.join(info.get('originals', [ticker]))
            ratio     = info.get('ratio', 'See sources')
            badges    = source_badges(info.get('sources', []))
            splits_rows += (
                f'<tr><td><strong>{ticker}</strong></td>'
                f'<td>{originals}</td>'
                f'<td>{ratio}</td>'
                f'<td>{badges}</td></tr>'
            )
        splits_html = f"""
        <h3>&#9986; Stock Splits (ex-date: {report_date})</h3>
        <table border="1" cellpadding="6" cellspacing="0"
               style="border-collapse:collapse;width:100%">
          <thead style="background:#2c3e50;color:#fff">
            <tr><th>Underlying</th><th>Position Ticker(s)</th>
                <th>Ratio</th><th>Confirmed By</th></tr>
          </thead>
          <tbody>{splits_rows}</tbody>
        </table>
        """
    else:
        splits_html = '<p><strong>Stock Splits:</strong> None found for tomorrow.</p>'

    # Dividends table
    div_rows = ''
    if dividends:
        for ticker, info in sorted(dividends.items()):
            originals = ', '.join(info.get('originals', [ticker]))
            amount    = info.get('amount', '')
            badges    = source_badges(info.get('sources', []))
            div_rows += (
                f'<tr><td><strong>{ticker}</strong></td>'
                f'<td>{originals}</td>'
                f'<td>{amount}</td>'
                f'<td>{badges}</td></tr>'
            )
        div_html = f"""
        <h3>&#128181; Ex-Dividend Dates (ex-date: {report_date})</h3>
        <table border="1" cellpadding="6" cellspacing="0"
               style="border-collapse:collapse;width:100%">
          <thead style="background:#27ae60;color:#fff">
            <tr><th>Underlying</th><th>Position Ticker(s)</th>
                <th>Dividend Amount</th><th>Confirmed By</th></tr>
          </thead>
          <tbody>{div_rows}</tbody>
        </table>
        """
    else:
        div_html = '<p><strong>Dividends:</strong> None found for tomorrow.</p>'

    return splits_html + '<br/>' + div_html
